[phases.setup]
pkgs = ["python310", "flask", "tensorflow==2.10.1"]  # Add any other packages you need


[phases.start]
cmd = "python manage.py runserver 0.0.0.0:5000"  # Use Flask start command if that's applicable

